spring.application.name=Vivatech

spring.datasource.url=jdbc:mysql://localhost:3306/vivatechrnd
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

fast2sms.api.key=AJ42ULmaSBPpN5t1vQf8D9rTqdVHinIkRsOu3hoXF6C0exyZWMuXx7wW0NMgEviJTnePmALQY1l9jcpf