spring.application.name=Vivatech

spring.datasource.url=jdbc:mysql://localhost:3306/vivatechrnd
spring.datasource.username=Your_username
spring.datasource.password=Your_password

spring.jpa.hibernate.ddl-auto=update

fast2sms.api.key=Your_fast2sms_api_key

secret.key=Your_secret_key